# language: node_js

# node_js:
#   - "14"

# install:
#   - npm install

# script:
#   - npm test

sudo: required
services:
  - docker
before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client